<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTz8gLMs\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTz8gLMs/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTz8gLMs.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerTz8gLMs\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerTz8gLMs\srcProdProjectContainer(array(
    'container.build_hash' => 'Tz8gLMs',
    'container.build_id' => 'f21c62ec',
    'container.build_time' => 1542532868,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTz8gLMs');
