<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnWGeHx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnWGeHx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMnWGeHx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMnWGeHx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMnWGeHx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MnWGeHx',
    'container.build_id' => '633790d3',
    'container.build_time' => 1541356695,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnWGeHx');
