<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBpInTQH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBpInTQH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBpInTQH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBpInTQH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBpInTQH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BpInTQH',
    'container.build_id' => 'fb54df46',
    'container.build_time' => 1541343336,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBpInTQH');
