<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WeatherHist extends \App\Entity\WeatherHist implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'localita', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'date', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmedia', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmin', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmax', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'puntorugiada', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'perc_umidita', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'visib_km', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventomedia_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventomax_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventoraffica_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pressioneslm_mb', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pressionemedia_mb', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pioggia_mm', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'fenomeni'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'localita', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'date', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmedia', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmin', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'tmax', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'puntorugiada', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'perc_umidita', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'visib_km', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventomedia_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventomax_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'ventoraffica_kmh', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pressioneslm_mb', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pressionemedia_mb', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'pioggia_mm', '' . "\0" . 'App\\Entity\\WeatherHist' . "\0" . 'fenomeni'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WeatherHist $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalita(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalita', []);

        return parent::getLocalita();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalita(string $localita): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalita', [$localita]);

        return parent::setLocalita($localita);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getTmedia(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTmedia', []);

        return parent::getTmedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTmedia(int $tmedia): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTmedia', [$tmedia]);

        return parent::setTmedia($tmedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTmin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTmin', []);

        return parent::getTmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTmin(int $tmin): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTmin', [$tmin]);

        return parent::setTmin($tmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTmax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTmax', []);

        return parent::getTmax();
    }

    /**
     * {@inheritDoc}
     */
    public function setTmax(int $tmax): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTmax', [$tmax]);

        return parent::setTmax($tmax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntorugiada(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntorugiada', []);

        return parent::getPuntorugiada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntorugiada(int $puntorugiada): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntorugiada', [$puntorugiada]);

        return parent::setPuntorugiada($puntorugiada);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercUmidita(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercUmidita', []);

        return parent::getPercUmidita();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercUmidita(int $perc_umidita): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercUmidita', [$perc_umidita]);

        return parent::setPercUmidita($perc_umidita);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibKm(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibKm', []);

        return parent::getVisibKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibKm(int $visib_km): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibKm', [$visib_km]);

        return parent::setVisibKm($visib_km);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentomediaKmh(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentomediaKmh', []);

        return parent::getVentomediaKmh();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentomediaKmh(int $ventomedia_kmh): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentomediaKmh', [$ventomedia_kmh]);

        return parent::setVentomediaKmh($ventomedia_kmh);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentomaxKmh(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentomaxKmh', []);

        return parent::getVentomaxKmh();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentomaxKmh(int $ventomax_kmh): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentomaxKmh', [$ventomax_kmh]);

        return parent::setVentomaxKmh($ventomax_kmh);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentorafficaKmh(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentorafficaKmh', []);

        return parent::getVentorafficaKmh();
    }

    /**
     * {@inheritDoc}
     */
    public function setVentorafficaKmh(int $ventoraffica_kmh): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVentorafficaKmh', [$ventoraffica_kmh]);

        return parent::setVentorafficaKmh($ventoraffica_kmh);
    }

    /**
     * {@inheritDoc}
     */
    public function getPressioneslmMb(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPressioneslmMb', []);

        return parent::getPressioneslmMb();
    }

    /**
     * {@inheritDoc}
     */
    public function setPressioneslmMb(int $pressioneslm_mb): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPressioneslmMb', [$pressioneslm_mb]);

        return parent::setPressioneslmMb($pressioneslm_mb);
    }

    /**
     * {@inheritDoc}
     */
    public function getPressionemediaMb(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPressionemediaMb', []);

        return parent::getPressionemediaMb();
    }

    /**
     * {@inheritDoc}
     */
    public function setPressionemediaMb(int $pressionemedia_mb): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPressionemediaMb', [$pressionemedia_mb]);

        return parent::setPressionemediaMb($pressionemedia_mb);
    }

    /**
     * {@inheritDoc}
     */
    public function getPioggiaMm(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPioggiaMm', []);

        return parent::getPioggiaMm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPioggiaMm(int $pioggia_mm): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPioggiaMm', [$pioggia_mm]);

        return parent::setPioggiaMm($pioggia_mm);
    }

    /**
     * {@inheritDoc}
     */
    public function getFenomeni(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenomeni', []);

        return parent::getFenomeni();
    }

    /**
     * {@inheritDoc}
     */
    public function setFenomeni(string $fenomeni): \App\Entity\WeatherHist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenomeni', [$fenomeni]);

        return parent::setFenomeni($fenomeni);
    }

}
